// C++ includes
#include <iostream>
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <map>
#include <string>
#include <sstream>
#include <utility>
#include <vector>
#include <functional>

// ROOT includes
#include "TROOT.h"
#include "TSystem.h"
#include "TApplication.h"
#include "TCollection.h"
#include "TClonesArray.h"
#include "TFile.h"
#include "TChain.h"
#include "TTree.h"
#include "TBranch.h"
#include "TObject.h"
#include "TCanvas.h"
#include "TH1.h"
#include "TH2.h"
#include "THStack.h"
#include "TStyle.h"
#include "TColor.h"
#include "TLegend.h"
#include "TPaveText.h"
#include "TMath.h"
#include "TRandom3.h"
#include "TLorentzVector.h"
#include "TVector2.h"
#include "TVector3.h"
#include "TString.h"
#include "TCut.h"
